### ISSUE TITLE
Can't click pages

### ISSUE THREAD

**Issue by davidnathanael** [Kurounin/PaginationBlaze#1]
The pagination bar is rendered but clicking on pages doesnt change data. When i disable [fullpagejs](https://atmospherejs.com/estatedev/fullpage) it works fine. Any idea to make them work together?

**Comment by Kurounin** [comment]
I installed that package and put the required mark-up for it, and inside a section I added a pagination, yet nothing seemed to change. Everything was working fine. Check if the click is registered (debug using chrome).
