### ISSUE TITLE
onClick not firing

### ISSUE THREAD

**Issue by odesey** [Kurounin/PaginationBlaze#2]
I defined the following in my `page.html` file 
`{{> defaultBootstrapPaginator pagination=templatePagination limit=10 containerClass="text-center" onClick=clickEvent}}`

and in my `page.js` file I have:

``` javascript
Template.page.helpers({
    templatePagination: function () {
        return Template.instance().pagination;
    },
    documents: function () {
        return Template.instance().pagination.getPage();
    },
    // optional helper used to return a callback that should be executed before changing the page
    clickEvent: function() {
        return function(e, templateInstance, clickedPage) {
            e.preventDefault();
            console.log('Changing page from ', templateInstance.data.pagination.currentPage(), ' to ', clickedPage);
        };
    }
});
```

The clickEvent helper never fires.

I am using:
`kurounin:pagination@1.0.11`
 `kurounin:pagination-blaze@1.0.2`

**Comment by Kurounin** [comment]
It should be working. Check for typos and if you put the helper in the correct template.
I created an example repository so you can see this in action:
https://github.com/Kurounin/PaginationExample

**Comment by odesey** [comment]
Turns out I needed to stop and start the meteor server for the changes to of the updated package to take effect.

Works now as expected.

Thanks.
