### ISSUE TITLE
Getting error on server side while adding this package

### ISSUE THREAD

**Issue by krashna-deligence** [Kurounin/PaginationBlaze#5]
Hello,

I am using meteor 1.6 (Updated), and this package is not working on updated meteor. i also update this package but still getting below error. I have installed `1.0.2` and `1.0.5` versions of this package.

![screenshot from 2017-12-07 10-51-19](https://user-images.githubusercontent.com/33921151/33700035-b5e57250-db3c-11e7-92b0-a01c61ad7f71.png)

Please advice

**Comment by Kurounin** [comment]
Hi,

I tried this package on version 1.6 and I did not encounter the error. You can check this [example repository ](https://github.com/Kurounin/PaginationExample) and compare the package versions (& npm packages) with your own.
